#!/bin/python3
import os
import sys
import io
from os import path
import executer
from executer import NonDirName, InvalidSyntax, InvalidArgument
from executer import NonFileName, InvalidDir

Demiurge = executer.Executer()


class Terminal:
    def __init__(self, out_stream=sys.stdout, err_stream=sys.stderr):
        self.home_dir = path.expanduser("~")
        self.last_dir = os.getcwd()
        self.cur_dir_name = os.getcwd()
        self.out_stream = out_stream
        self.err_stream = err_stream

    def __deprivat(self, priv_path: str):
        """
        makes path absolute
        """
        if priv_path[0] == "~":
            place = path.expanduser(priv_path)
        elif priv_path[0] == "/":
            place = priv_path
        elif priv_path == "-":
            place = self.last_dir
        else:
            place = self.cur_dir_name + "/" + priv_path
        return path.realpath(place)

    def __chdir(self, subcommand_list):
        """
        changes directory
        """
        if len(subcommand_list) != 1 or not isinstance(subcommand_list[0], str):
            self.err_stream.write("too few arguments\n")
            return
        if len(subcommand_list) != 1 or not isinstance(subcommand_list[0], str):
            self.err_stream.write("invalid syntax\n")
            return

        place = os.path.realpath(self.__deprivat(subcommand_list[0]))
        if os.path.isdir(place):
            self.last_dir = self.cur_dir_name
            self.cur_dir_name = place
        else:
            self.err_stream.write("this directory doesn't exist\n")

    def cur_dir_name_short(self):
        """
        :return: current directory name
        """
        ans = self.cur_dir_name
        if ans[0:len(self.home_dir)] == self.home_dir:
            ans = '~' + ans[len(self.home_dir):]
        return ans

    def __listdir(self, subcommand_list: list):
        """
        prints list of directory
        """
        flags = []
        for part in enumerate(subcommand_list):
            if part[1][0] == "-" and len(part[1]) != 1:
                flags += list(part[1])
                flags.remove("-")
                subcommand_list.pop(part[0])

        if not subcommand_list:
            subcommand_list.append(self.cur_dir_name)
        elif len(subcommand_list) != 1 or not isinstance(subcommand_list[0], str):
            self.err_stream.write("too few arguments\n")
            return

        place = self.__deprivat(subcommand_list[0])
        try:
            self.out_stream.write(Demiurge.listdir(place, "".join(flags)))
        except NonDirName:
            self.err_stream.write("not directory name\n")

    def __copy(self, subcommand_list):
        """
        copies file
        """
        if not subcommand_list:
            subcommand_list[0] = self.cur_dir_name
        elif len(subcommand_list) != 2:
            self.err_stream.write("too few arguments\n")
            return

        input_stream = self.__deprivat(subcommand_list[0])
        output = self.__deprivat(subcommand_list[1])
        try:
            Demiurge.copy(input_stream, output)
        except NonDirName:
            self.err_stream.write("incorrect input or output path\n")
        except InvalidSyntax:
            self.err_stream.write("incorrect syntax\n")

    def move(self, subcommand_list):
        """
        moves or renames file
        """
        if not subcommand_list:
            subcommand_list[0] = self.cur_dir_name
        elif len(subcommand_list) != 2:
            self.err_stream.write("too few arguments\n")
            return

        input_stream = self.__deprivat(subcommand_list[0])
        output = self.__deprivat(subcommand_list[1])
        try:
            Demiurge.move(input_stream, output)
        except NonDirName:
            self.err_stream.write("incorrect input or output path\n")
        except InvalidSyntax:
            self.err_stream.write("incorrect syntax\n")

    def remove_file(self, subcommand_list: list):
        """
        removes file
        """
        if len(subcommand_list) != 1:
            self.err_stream.write("invalid num of arguments\n")
            return
        if not subcommand_list:
            subcommand_list[0] = self.cur_dir_name

        filename = self.__deprivat(subcommand_list[0])
        try:
            Demiurge.remove_file(filename)
        except NonFileName:
            self.err_stream.write("not file name\n")

    def echo(self, subcommand_list: list):
        """
        prints its argument
        """
        my_str = " ".join(subcommand_list)
        if my_str[0] == my_str[-1] == '"':
            my_str = my_str[1:-1]
        self.out_stream.write(my_str)

    def rmdir(self, subcommand_list: list):
        """
        removes empty directory
        """
        if not subcommand_list:
            subcommand_list.append(self.cur_dir_name)
        elif len(subcommand_list) != 1 or not isinstance(subcommand_list[0], str):
            self.err_stream.write("too few arguments\n")
            return

        place = self.__deprivat(subcommand_list[0])
        if path.realpath(place) == path.realpath(self.cur_dir_name):
            self.err_stream.write("you try to delete current directory\n")
            return
        if path.realpath(place) == path.realpath(self.last_dir):
            self.last_dir = self.cur_dir_name
        try:
            Demiurge.remove_directory(place)
        except NonDirName:
            self.err_stream.write("not directory name\n")
        except InvalidArgument:
            self.err_stream.write("directory is not empty\n")

    def position(self):
        """
        :return: user info
        """
        user = "\033[32m{0}@{1}".format(os.getlogin(), os.uname().nodename)
        cwd = "\033[34m" + self.cur_dir_name_short()
        ans = user + "\033[37m:" + cwd + "\033[37m$" + "\033[0m"
        return ans

    def mkdir(self, subcommand_list):
        """
        creates directory
        """
        if not subcommand_list:
            subcommand_list[0] = self.cur_dir_name
        elif len(subcommand_list) != 1:
            self.err_stream.write("incorrect number of arguments\n")
            return

        output = self.__deprivat(subcommand_list[0])
        try:
            Demiurge.make_directory(output)
        except NonDirName:
            self.err_stream.write("incorrect output path\n")
        except InvalidSyntax:
            self.err_stream.write("incorrect syntax\n")

    def pwd(self):
        """
        path to current directory
        """
        self.out_stream.write(self.cur_dir_name + "\n")

    def xargs(self, subcommand_list: list, instream):
        """
        takes input stream and puts it as argument to the end of next command
        """
        empty_stream = io.StringIO()
        self.run(subcommand_list + [instream.read()], empty_stream)

    def cat(self, subcommand_list: list):
        """
        prints file content
        """
        if len(subcommand_list) != 1:
            self.err_stream.write("incorrect number of arguments\n")
        filename = self.__deprivat(subcommand_list[0])
        try:
            self.out_stream.write(Demiurge.cat(filename))
        except NonFileName:
            self.err_stream.write("not file name\n")

    def touch(self, subcommand_list: list):
        """
        creates empty file
        """
        if len(subcommand_list) != 1:
            self.err_stream.write("incorrect number of arguments\n")
        filename = self.__deprivat(subcommand_list[0])
        try:
            Demiurge.touch(filename)
        except InvalidArgument:
            self.err_stream.write("file already exist\n")
        except InvalidDir:
            self.err_stream.write("directory doesn't exist\n")

    def subprocess(self, subcommand_list, instream):
        """
        rus subprocess
        """
        in_stream = io.StringIO(instream.read())
        try:
            Demiurge.subprocess(self.cur_dir_name, subcommand_list, in_stream,
                                self.out_stream, self.err_stream)
        except Exception as ex:
            self.err_stream.write(str(ex) + "\n")

    def continue_run(self, command_run: list):
        """
        helper for run function
        """
        ind = True
        if command_run[0] == "cd":
            command_run.pop(0)
            self.__chdir(command_run)
            ind = False
        elif command_run[0] == "ls":
            command_run.pop(0)
            self.__listdir(command_run)
            ind = False
        elif command_run[0] == "cp":
            command_run.pop(0)
            self.__copy(command_run)
            ind = False
        elif command_run[0] == "mv":
            command_run.pop(0)
            self.move(command_run)
            ind = False
        elif command_run[0] == "echo":
            command_run.pop(0)
            self.echo(command_run)
            ind = False
        elif command_run[0] == "rm":
            command_run.pop(0)
            self.remove_file(command_run)
            ind = False
        elif command_run[0] == "mkdir":
            command_run.pop(0)
            self.mkdir(command_run)
            ind = False
        elif command_run[0] == "rmdir":
            command_run.pop(0)
            self.rmdir(command_run)
            ind = False
        return ind

    def run(self, command_run: list, in_stream):
        """
        runs command from list
        """
        if not command_run:
            self.out_stream.write("\r")
        elif command_run[0] == "pwd":
            self.pwd()
        elif command_run[0] == "xargs":
            command_run.pop(0)
            self.xargs(command_run, in_stream)
        elif command_run[0] == "cat":
            command_run.pop(0)
            self.cat(command_run)
        elif command_run[0] == "touch":
            command_run.pop(0)
            self.touch(command_run)
        elif self.continue_run(command_run):
            self.subprocess(command_run, in_stream)


    def parse_clear(self, command_list_c: list, begin: int, in_stream):
        """
        simple parsing
        """
        ans = list()
        ans.append("")
        end = begin
        i = 0
        prev_sign = [False, False]
        size = len(command_list_c)
        while end < size:
            char = command_list_c[end]
            if prev_sign[1]:
                if char == '(':
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = 1
                    if len(ans) > 1:
                        empty_stream = io.StringIO()
                        contin = inter.parse_brackets(command_list_c, end,
                                                      empty_stream)
                    else:
                        contin = inter.parse_brackets(command_list_c, end,
                                                      in_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter.out_stream.getvalue()
                    i += 1
                    ans.append("")
                    end = contin - 1
                else:
                    ans[i] += '$'
                    end -= 1
                prev_sign[1] = False
            elif prev_sign[0]:
                ans[i] += char
                prev_sign[0] = False
            else:
                if char == '\\':
                    prev_sign[0] = True
                elif char == '$':
                    prev_sign[1] = True
                elif char == " ":
                    i += 1
                    ans.append("")
                elif char == '"':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parse_double_quotes(command_list_c, end,
                                                       empty_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter_stream.read()
                    i += 1
                    ans.append("")
                    end = contin - 1
                elif char == "'":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parse_quotes(command_list_c, end)
                    if ans[i] != "":
                        i += 1
                    ans[i] = inter_stream.read()
                    i += 1
                    end = contin - 1
                elif char == "|":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    ans = list(filter(lambda x: x != '', ans))
                    inter.run(ans, in_stream)
                    in_stream = inter.out_stream
                    ans = [""]
                    i = 0
                elif char == ")":
                    raise SyntaxError
                else:
                    ans[i] += char
            pot = list(filter(lambda x: x != '', ans))
            if ans[-1] == "":
                ans = pot + [""]
            else:
                ans = pot
            i = len(ans) - 1
            end += 1
        ans = list(filter(lambda x: x != '', ans))
        self.run(ans, in_stream)
        return end

    def parse_double_quotes(self, command_list: list, begin: int,
                            in_stream) -> int:
        """
        parses expressions in double quotes
        """
        if in_stream == int:
            raise InvalidArgument
        ans = ""
        end = begin
        escape_char = False
        dollar_is_prev = False
        size = len(command_list)
        while end < size:
            char = command_list[end]
            if dollar_is_prev:
                if char == '(':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parse_brackets(command_list, end,
                                                  empty_stream)
                    ans += inter_stream.read()

                    end = contin - 1
                else:
                    ans += '$'
                    end -= 1
                dollar_is_prev = False
            elif escape_char:
                ans += char
                escape_char = False
            else:
                if char == '\\':
                    escape_char = True
                elif char == '$':
                    dollar_is_prev = True
                elif char == '"':
                    end += 1
                    self.out_stream.write(ans)
                    return end
                else:
                    ans += char

            end += 1
        raise SyntaxError

    def parse_quotes(self, command_list: list, begin: int) -> int:
        """
        parses expressions in quotes
        """
        begin += 1
        ans = ""
        end = begin
        for char in command_list[begin:]:
            if char == "'":
                end += 1
                self.out_stream.write(ans)
                return end
            ans += char
            end += 1
        raise SyntaxError

    def parse_brackets(self, command_list: list, begin: int, in_stream) -> int:
        """
        parses expressions in brackets
        """
        ans = [""]

        end = begin
        i = 0
        escape_char = False
        dollar_is_prev = False
        size = len(command_list)
        while end < size:
            char = command_list[end]
            if dollar_is_prev:
                if char == '(':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parse_brackets(command_list, end,
                                                  empty_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter_stream.read()
                    i += 1
                    ans.append("")
                    end = contin - 1
                else:
                    ans[i] += '$'
                    end -= 1
                dollar_is_prev = False
            elif escape_char:
                ans[i] += char
                escape_char = False
            else:
                if char == '\\':
                    escape_char = True
                elif char == '$':
                    dollar_is_prev = True
                elif char == " ":
                    i += 1
                    ans.append("")
                elif char == '"':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parse_double_quotes(command_list, end,
                                                       empty_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter_stream.read()
                    i += 1
                    ans.append("")
                    end = contin - 1
                elif char == "'":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parse_quotes(command_list, end)
                    if ans[i] != "":
                        i += 1
                    ans[i] = inter_stream.read()
                    i += 1
                    end = contin - 1
                elif char == "|":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    ans = list(filter(lambda x: x != '', ans))
                    inter.run(ans, in_stream)
                    in_stream = inter.out_stream
                    ans = []
                    i = 0
                elif char == ")":
                    end += 1
                    ans = list(filter(lambda x: x != '', ans))
                    self.run(ans, in_stream)
                    return end
                else:
                    ans[i] += char

            end += 1
        raise SyntaxError

    def parse(self, command_list: str):
        """
        starts parsing
        """
        pre_parsing = list(command_list)
        empty_stream = io.StringIO()
        try:
            self.parse_clear(pre_parsing, 0, empty_stream)
        except SyntaxError:
            sys.stderr.write("invalid syntax\n")


A = Terminal()
print()
while True:
    try:
        print(A.position(), end="")
        COMMAND = input()
        A.parse(COMMAND)

    except KeyboardInterrupt:
        print("\nI remember what you did to me\033[0m")
        break
