#!/bin/python3
import os
import sys
sys.path.insert(1, "executer_dir")
from executer import Executer
import executer
from time import sleep
import re
from os import path
import io

demiurge = executer.Executer()


from executer import NonDirName, InvalidSyntax, InvalidArgument, NonFileName, InvalidDir, CurrentDirDeleting

class Terminal:
    def __init__(self, out_stream=sys.stdout, err_stream=sys.stderr):
        self.home_dir = path.expanduser("~")
        self.last_dir = os.getcwd()
        self.cur_dir_name = os.getcwd()
        self.out_stream = out_stream
        self.err_stream = err_stream

    def deprivat(self, priv_path: str):
        if priv_path[0] == "~":
            place = path.expanduser(priv_path)
        elif priv_path[0] == "/":
            place = priv_path
        elif priv_path == "-":
            place = self.last_dir
        else:
            place = self.cur_dir_name + "/" + priv_path
        return path.realpath(place)

    def chdir(self, subcommand):
        if len(subcommand) != 1 or type(subcommand[0]) is not str:
            self.err_stream.write("too few arguments\n")
            return
        if len(subcommand) != 1 or type(subcommand[0]) is not str:
            self.err_stream.write("invalid syntax\n")
            return

        place = os.path.realpath(self.deprivat(subcommand[0]))
        if os.path.isdir(place):
            self.last_dir = self.cur_dir_name
            self.cur_dir_name = place
        else:
            self.err_stream.write("this directory doesn't exist\n")

    def cur_dir_name_short(self):
        ans = self.cur_dir_name
        if ans[0:len(self.home_dir)] == self.home_dir:
            ans = '~' + ans[len(self.home_dir):]
        return ans

    def listdir(self, subcommand: list):
        flags = []
        for part in enumerate(subcommand):
            if part[1][0] == "-" and len(part[1]) != 1:
                flags += list(part[1])
                flags.remove("-")
                subcommand.pop(part[0])

        if not subcommand:
            subcommand.append(self.cur_dir_name)
        elif len(subcommand) != 1 or type(subcommand[0]) is not str:
            self.err_stream.write("too few arguments\n")
            return

        place = self.deprivat(subcommand[0])
        try:
            self.out_stream.write(demiurge.listdir(place, "".join(flags)))
        except NonDirName:
            self.err_stream.write("not directory name\n")

    def copy(self, subcommand):
        if not subcommand:
            subcommand[0] = self.cur_dir_name
        elif len(subcommand) != 2:
            self.err_stream.write("too few arguments\n")
            return

        input = self.deprivat(subcommand[0])
        output = self.deprivat(subcommand[1])
        try:
            demiurge.copy(input, output)
        except NonDirName:
            self.err_stream.write("incorrect input or output path\n")
        except InvalidSyntax:
            self.err_stream.write("incorrect syntax\n")

    def move(self, subcommand):
        if not subcommand:
            subcommand[0] = self.cur_dir_name
        elif len(subcommand) != 2:
            self.err_stream.write("too few arguments\n")
            return

        input = self.deprivat(subcommand[0])
        output = self.deprivat(subcommand[1])
        try:
            demiurge.move(input, output)
        except NonDirName:
            self.err_stream.write("incorrect input or output path\n")
        except InvalidSyntax:
            self.err_stream.write("incorrect syntax\n")

    def remove_file(self, subcommand: list):
        if len(subcommand) != 1:
            self.err_stream.write("invalid num of arguments\n")
            return
        elif not subcommand:
            subcommand[0] = self.cur_dir_name

        filename = self.deprivat(subcommand[0])
        try:
            demiurge.remove_file(filename)
        except NonFileName:
            self.err_stream.write("not file name\n")

    def echo(self, subcommand: list):
        my_str = " ".join(subcommand)
        if my_str[0] == my_str[-1] == '"':
            my_str = my_str[1:-1]
        self.out_stream.write(my_str)

    def rmdir(self, subcommand: list):
        if not subcommand:
            subcommand.append(self.cur_dir_name)
        elif len(subcommand) != 1 or type(subcommand[0]) is not str:
            self.err_stream.write("too few arguments\n")
            return

        place = self.deprivat(subcommand[0])
        if path.realpath(place) == path.realpath(self.cur_dir_name):
            self.err_stream.write("you try to delete current directory\n")
            return
        if path.realpath(place) == path.realpath(self.last_dir):
            self.last_dir = self.cur_dir_name
        try:
            demiurge.remove_directory(place)
        except NonDirName:
            self.err_stream.write("not directory name\n")
        except InvalidArgument:
            self.err_stream.write("directory is not empty\n")

    def position(self):
        user = "\033[32m{0}@{1}".format(os.getlogin(), os.uname().nodename)
        cwd = "\033[34m" + self.cur_dir_name_short()
        ans = user + "\033[37m:" + cwd + "\033[37m$"
        return ans

    def mkdir(self, subcommand):
        if not subcommand:
            subcommand[0] = self.cur_dir_name
        elif len(subcommand) != 1:
            self.err_stream.write("incorrect number of arguments\n")
            return

        output = self.deprivat(subcommand[0])
        try:
            demiurge.make_directory(output)
        except NonDirName:
            self.err_stream.write("incorrect output path\n")
        except InvalidSyntax:
            self.err_stream.write("incorrect syntax\n")

    def pwd(self):
        self.out_stream.write(self.cur_dir_name + "\n")

    def xargs(self, subcommand: list, instream):
        empty_stream = io.StringIO()
        self.run(subcommand + [instream.read()], empty_stream)

    def cat(self, subcommand: list):
        if len(subcommand) != 1:
            self.err_stream.write("incorrect number of arguments\n")
        filename = self.deprivat(subcommand[0])
        try:
            self.out_stream.write(demiurge.cat(filename))
        except NonFileName:
            self.err_stream.write("not file name\n")

    def touch(self, subcommand: list):
        if len(subcommand) != 1:
            self.err_stream.write("incorrect number of arguments\n")
        filename = self.deprivat(subcommand[0])
        try:
            demiurge.touch(filename)
        except InvalidArgument:
            self.err_stream.write("file already exist\n")
        except InvalidDir:
            self.err_stream.write("directory doesn't exist\n")

    def subprocess(self, subcommand, instream):
        in_stream = io.StringIO(instream.read())
        try:
            demiurge.subprocess(self.cur_dir_name, subcommand, in_stream, self.out_stream, self.err_stream)
        except Exception as ex:
            self.err_stream.write(str(ex) + "\n")
        pass

    def run(self, command: list, in_stream):
        if command == []:
            self.out_stream.write("\r")
        elif command[0] == "cd":
            command.pop(0)
            self.chdir(command)
        elif command[0] == "ls":
            command.pop(0)
            self.listdir(command)
        elif command[0] == "cp":
            command.pop(0)
            self.copy(command)
        elif command[0] == "mv":
            command.pop(0)
            self.move(command)
        elif command[0] == "echo":
            command.pop(0)
            self.echo(command)
        elif command[0] == "rm":
            command.pop(0)
            self.remove_file(command)
        elif command[0] == "mkdir":
            command.pop(0)
            self.mkdir(command)
        elif command[0] == "rmdir":
            command.pop(0)
            self.rmdir(command)
        elif command[0] == "pwd":
            self.pwd()
        elif command[0] == "xargs":
            command.pop(0)
            self.xargs(command, in_stream)
        elif command[0] == "cat":
            command.pop(0)
            self.cat(command)
        elif command[0] == "touch":
            command.pop(0)
            self.touch(command)
        else:
            self.subprocess(command, in_stream)

    def parseClear(self, command: list, begin: int, in_stream):
        ans = []
        ans.append("")
        end = begin
        i = 0
        escape_char = False
        dollar_is_prev = False
        size = len(command)
        while end < size:
            char = command[end]
            if dollar_is_prev:
                if char == '(':
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = ""
                    if len(ans) > 1:
                        empty_stream = io.StringIO()
                        contin = inter.parseBrackets(command, end, empty_stream)
                    else:
                        contin = inter.parseBrackets(command, end, in_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter.out_stream.getvalue()
                    i += 1
                    ans.append("")
                    end = contin - 1
                else:
                    ans[i] += '$'
                    end -= 1
                dollar_is_prev = False
            elif escape_char:
                ans[i] += char
                escape_char = False
            else:
                if char == '\\':
                    escape_char = True
                elif char == '$':
                    dollar_is_prev = True
                elif char == " ":
                    i += 1
                    ans.append("")
                elif char == '"':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parseDoubleQuotes(command, end, empty_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter_stream.read()
                    i += 1
                    ans.append("")
                    end = contin - 1
                elif char == "'":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parseQuotes(command, end)
                    if ans[i] != "":
                        i += 1
                    ans[i] = inter_stream.read()
                    i += 1
                    end = contin - 1
                elif char == "|":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    ans = list(filter(lambda x: x != '', ans))
                    inter.run(ans, in_stream)
                    in_stream = inter.out_stream
                    ans = [""]
                    i = 0
                elif char == ")":
                    raise SyntaxError
                else:
                    ans[i] += char
            pot = list(filter(lambda x: x != '', ans))
            if ans[-1] == "":
                ans = pot + [""]
            else:
                ans = pot
            i = len(ans) - 1
            end += 1
        ans = list(filter(lambda x: x != '', ans))
        self.run(ans, in_stream)
        return end

    def parseDoubleQuotes(self, command: list, begin: int, in_stream) -> int:
        ans = ""
        end = begin
        escape_char = False
        dollar_is_prev = False
        size = len(command)
        while end < size:
            char = command[end]
            if dollar_is_prev:
                if char == '(':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parseBrackets(command, end, empty_stream)
                    ans += inter_stream.read()

                    end = contin - 1
                else:
                    ans += '$'
                    end -= 1
                dollar_is_prev = False
            elif escape_char:
                ans += char
                escape_char = False
            else:
                if char == '\\':
                    escape_char = True
                elif char == '$':
                    dollar_is_prev = True
                elif char == '"':
                    end += 1
                    self.out_stream.write(ans)
                    return end
                else:
                    ans += char

            end += 1
        raise SyntaxError

    def parseQuotes(self, command: list, begin: int) -> int:
        begin += 1
        ans = ""
        end = begin
        for char in command[begin:]:
            if char == "'":
                end += 1
                self.out_stream.write(ans)
                return end
            else:
                ans += char
            end += 1
        raise SyntaxError

    def parseBrackets(self, command: list, begin: int, in_stream) -> int:
        ans = [""]

        end = begin
        i = 0
        escape_char = False
        dollar_is_prev = False
        size = len(command)
        while end < size:
            char = command[end]
            if dollar_is_prev:
                if char == '(':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parseBrackets(command, end, empty_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter_stream.read()
                    i += 1
                    ans.append("")
                    end = contin - 1
                else:
                    ans[i] += '$'
                    end -= 1
                dollar_is_prev = False
            elif escape_char:
                ans[i] += char
                escape_char = False
            else:
                if char == '\\':
                    escape_char = True
                elif char == '$':
                    dollar_is_prev = True
                elif char == " ":
                    i += 1
                    ans.append("")
                elif char == '"':
                    end += 1
                    inter_stream = io.StringIO()
                    empty_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parseDoubleQuotes(command, end, empty_stream)
                    if ans[i] != "":
                        i += 1
                    else:
                        ans.append("")
                    ans[i] = inter_stream.read()
                    i += 1
                    ans.append("")
                    end = contin - 1
                elif char == "'":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    contin = inter.parseQuotes(command, end)
                    if ans[i] != "":
                        i += 1
                    ans[i] = inter_stream.read()
                    i += 1
                    end = contin - 1
                elif char == "|":
                    end += 1
                    inter_stream = io.StringIO()
                    inter = Terminal(inter_stream, self.err_stream)
                    ans = list(filter(lambda x: x != '', ans))
                    inter.run(ans, in_stream)
                    in_stream = inter.out_stream
                    ans = []
                    i = 0
                elif char == ")":
                    end += 1
                    ans = list(filter(lambda x: x != '', ans))
                    self.run(ans, in_stream)
                    return end
                else:
                    ans[i] += char

            end += 1
        raise SyntaxError

    def parse(self, command: str):
        pre_parsing = list(command)
        empty_stream = io.StringIO()
        try:
            self.parseClear(pre_parsing, 0, empty_stream)
        except SyntaxError:
            sys.stderr.write("invalid syntax\n")


a = Terminal()
print()
while True:
    try:
        print(a.position(), end="")
        command = input()
        a.parse(command)

    except KeyboardInterrupt:
        print("\nI remember what you did to me\033[0m")

        exit()
